services:
  - type: web
    name: streamify-backend
    env: node
    rootDir: backend
    region: oregon
    plan: free # Change this to 'starter' or higher for production if needed
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # The following environment variables need to be securely set in the Render Dashboard.
      # By specifying sync: false, Render knows they are required but won't overwrite 
      # your dashboard values with empty ones from this file.
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
